---
settings:
  name: StorageGRID 11.7
  search: storagegrid-enable,storagegrid-117
  downlevel: true
  internal:
    pdf_enabled: false
    termcheck_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
    hide_language_selector: false
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: StorageGRID 11.7 Dokumente
    url: "/index.html"
  - title: Versionshinweise
    url: "/release-notes/index.html"
  - title: Los geht's
    entries:
    - section: primer
    - section: network
    - title: Schnellstart für StorageGRID
      url: "/primer/quick-start.html"
  - title: Installation und Upgrade
    entries:
    - section: installconfig
    - section: rhel
    - section: ubuntu
    - section: vmware
    - section: upgrade
  - title: Konfiguration und Management
    entries:
    - section: admin
    - section: ilm
    - section: harden
    - section: fabricpool
  - title: Verwenden Sie StorageGRID
    entries:
    - section: tenant
    - section: s3
    - section: swift
  - title: Monitoring und Fehlerbehebung
    entries:
    - section: monitor
    - section: troubleshoot
    - section: audit
  - title: Wartung
    entries:
    - section: expand
    - section: maintain
    - section: commonhardware
    - section: sg6100
    - section: sg6000
    - section: sg5700
    - section: sg5600
    - section: sg100-1000
  - title: Aktivieren Sie StorageGRID
    url: "/storagegrid-enable.html"
  - title: Andere Versionen
    url: "/earlier-versions.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: StorageGRID documentation
  repo: storagegrid-family
