---
settings:
  name: StorageGRID 11.7
  internal:
    pdf_enabled: false
    termcheck_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
    hide_language_selector: true
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr
sidebar:
  entries:
  - title: StorageGRID 11.7 Dokumente
    url: "/index.html"
  - title: Versionshinweise
    url: "/release-notes/index.html"
  - title: Los geht's
    entries:
    - section: primer
    - section: network
    - title: Schnellstart für StorageGRID
      url: "/primer/quick-start.html"
  - title: Installation und Upgrade
    entries:
    - section: installconfig
    - section: rhel
    - section: ubuntu
    - section: vmware
    - section: upgrade
  - title: Konfiguration und Management
    entries:
    - section: admin
    - section: ilm
    - section: harden
    - section: fabricpool
  - title: Verwenden Sie StorageGRID
    entries:
    - section: tenant
    - section: s3
    - section: swift
  - title: Monitoring und Fehlerbehebung
    entries:
    - section: monitor
    - section: troubleshoot
    - section: audit
  - title: Wartung
    entries:
    - section: expand
    - section: maintain
    - section: commonhardware
    - section: sg6100
    - section: sg6000
    - section: sg5700
    - section: sg5600
    - section: sg100-1000
  - title: Aktivieren Sie StorageGRID
    url: "/storagegrid-enable.html"
  - title: Frühere Versionen
    url: "/earlier-versions.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Los geht's
    links:
    - title: Versionshinweise
      url: "/release-notes/index.html"
    - title: Was ist neu
      url: "/upgrade/whats-new.html"
    - title: Weitere Informationen zu StorageGRID
      url: "/primer/index.html"
    - title: Netzwerkrichtlinien
      url: "/network/index.html"
    - title: Quick Start Guide für StorageGRID
      url: "/primer/quick-start.html"
  - title: Installation und Wartung von Hardware
    links:
    - title: Installation und Implementierung von Appliances
      url: "/installconfig/index.html"
    - title: Geräte warten
      url: "/maintain/index.html"
  - title: Software installieren und aktualisieren
    links:
    - title: Installieren Sie Red hat Enterprise Linux oder CentOS
      url: "/rhel/index.html"
    - title: Installieren Sie Ubuntu oder Debian
      url: "/ubuntu/index.html"
    - title: VMware installieren
      url: "/vmware/index.html"
    - title: Software-Upgrade
      url: "/upgrade/index.html"
  - title: Konfigurieren des Grids
    links:
    - title: StorageGRID verwalten
      url: "/admin/index.html"
    - title: Objektmanagement mit ILM
      url: "/ilm/index.html"
    - title: Systemhärtung
      url: "/harden/index.html"
    - title: Konfigurieren Sie StorageGRID für FabricPool
      url: "/fabricpool/index.html"
  - title: Verwalten von Objekten
    links:
    - title: Verwenden Sie ein Mandantenkonto
      url: "/tenant/index.html"
    - title: S3-REST-API VERWENDEN
      url: "/s3/index.html"
    - title: Swift REST API verwenden (veraltet)
      url: "/swift/index.html"
  - title: Überwachung und Wartung
    links:
    - title: Überwachen
      url: "/monitor/index.html"
    - title: Fehlerbehebung
      url: "/troubleshoot/index.html"
    - title: Prüfung von Audit-Protokollen
      url: "/audit/index.html"
    - title: Erweitern Sie Ihr Raster
      url: "/expand/index.html"
    - title: Wiederherstellung und Wartung
      url: "/maintain/index.html"
  - title: Demos und Lernprogramme
    links:
    - title: Informationen zur Aktivierung von StorageGRID
      url: https://docs.netapp.com/us-en/storagegrid-enable/index.html
    - title: StorageGRID-Videobibliothek
      url: https://www.youtube.com/playlist?list=PLdXI3bZJEw7nh2wGRA65iulXhtXwLiqrY
    - title: NetApp Learning Services
      url: https://www.netapp.com/support-and-training/netapp-university/
  - title: Mehr Ressourcen
    links:
    - title: StorageGRID Support-Seite
      url: https://mysupport.netapp.com/site/products/all/details/5d9f1107e01d9c0001ee50f6/downloads-tab
    - title: NetApp Interoperabilitäts-Matrix-Tool (IMT)
      url: https://imt.netapp.com/matrix/#welcome
    - title: StorageGRID Knowledge Base
      url: https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID
    - title: NetApp Blog
      url: https://netapp.com/blog/
    - title: NetApp Community
      url: https://community.netapp.com/
  - title: Frühere Versionen
    links:
    - title: StorageGRID 11.6-Dokumentation
      url: https://docs.netapp.com/us-en/storagegrid-116/index.html
    - title: StorageGRID 11.5-Dokumentation
      url: https://docs.netapp.com/us-en/storagegrid-115/index.html
    - title: StorageGRID 11.4-Dokumentation
      url: https://docs.netapp.com/sgws-114/index.jsp
    - title: StorageGRID 11.3-Dokumentation
      url: https://docs.netapp.com/sgws-113/index.jsp
