---
permalink: installconfig/configuring-bmc-interface.html 
sidebar: sidebar 
keywords: BMC, baseboard management controller, configure, setup, set up 
summary: 'Die Benutzeroberfläche für den Baseboard Management Controller \(BMC\) auf der SGF6112-, SG6000- oder Services-Appliance bietet Statusinformationen zur Hardware und ermöglicht Ihnen die Konfiguration von SNMP-Einstellungen und anderen Optionen für die Appliances.' 
---
= BMC-Schnittstelle: Überblick (SGF6112, SG6000, SG100 und SG1000)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Benutzeroberfläche des Baseboard Management Controllers (BMC) auf der SGF6112-, SG6000- oder Services-Appliance liefert Statusinformationen zur Hardware und ermöglicht Ihnen die Konfiguration von SNMP-Einstellungen und anderen Optionen für die Appliances.

Gehen Sie wie folgt vor, um den BMC bei der Installation des Geräts zu konfigurieren:

* link:../installconfig/changing-root-password-for-bmc-interface.html["Ändern Sie das Root-Passwort für die BMC-Schnittstelle"]
* link:../installconfig/setting-ip-address-for-bmc-management-port.html["Legen Sie die IP-Adresse für den BMC-Managementport fest"]
* link:../installconfig/accessing-bmc-interface.html["Greifen Sie auf die BMC-Schnittstelle zu"]
* link:../installconfig/configuring-snmp-settings-for-bmc.html["Konfigurieren Sie die SNMP-Einstellungen"]
* link:../installconfig/setting-up-email-notifications-for-alerts.html["E-Mail-Benachrichtigungen für BMC-Warnungen einrichten"]


[NOTE]
====
Wenn die Appliance bereits in einem Grid installiert wurde und StorageGRID-Software ausgeführt wird, gehen Sie wie folgt vor:

* link:../commonhardware/placing-appliance-into-maintenance-mode.html["Stellen Sie das Gerät in den Wartungsmodus"] Um auf das Installationsprogramm für die StorageGRID Appliance zuzugreifen.
* Siehe link:../installconfig/setting-ip-address-for-bmc-management-port.html["Legen Sie die IP-Adresse für den BMC-Managementport fest"] Für Informationen über den Zugriff auf die BMC-Schnittstelle mithilfe des StorageGRID-Appliance-Installationsprogramms.


====