---
permalink: installconfig/viewing-error-codes-for-sg6000-cn-controller.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, error codes, errors, error, codes, sg6000-cn 
summary: Wenn beim Starten des SG6000-CN Controllers ein Hardwarefehler auftritt, meldet der BMC einen Fehlercode. Bei Bedarf können Sie diese Fehlercodes über die BMC-Schnittstelle anzeigen und dann mit dem technischen Support zusammenarbeiten, um das Problem zu lösen. 
---
= Fehlercodes anzeigen (SG6000-CN-Controller)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn beim Starten des SG6000-CN Controllers ein Hardwarefehler auftritt, meldet der BMC einen Fehlercode. Bei Bedarf können Sie diese Fehlercodes über die BMC-Schnittstelle anzeigen und dann mit dem technischen Support zusammenarbeiten, um das Problem zu lösen.

.Bevor Sie beginnen
* Wissen Sie, wie Sie auf das BMC-Dashboard zugreifen können.


.Schritte
. Wählen Sie im BMC-Dashboard *BIOS POST Code* aus.
. Überprüfen Sie die angezeigten Informationen für den aktuellen Code und den vorherigen Code.
+
Wenn einer der folgenden Fehlercodes angezeigt wird, wenden Sie sich an den technischen Support, um das Problem zu beheben.

+
[cols="1a,3a"]
|===
| Codieren | Zeigt An 


 a| 
0x0E
 a| 
Der Mikrocode wurde nicht gefunden



 a| 
0x0F
 a| 
Mikrocode nicht geladen



 a| 
0x50
 a| 
Speicherinitialisierungsfehler. Ungültiger Speichertyp oder inkompatible Speichergeschwindigkeit.



 a| 
0x51
 a| 
Speicherinitialisierungsfehler. Der SPD-Lesewert ist fehlgeschlagen.



 a| 
0x52
 a| 
Speicherinitialisierungsfehler. Ungültige Speichergröße oder Speichermodule stimmen nicht überein.



 a| 
0x53
 a| 
Speicherinitialisierungsfehler. Kein verwendbarer Speicher erkannt.



 a| 
0x54
 a| 
Nicht angegebener Speicherinitialisierungsfehler



 a| 
0x55
 a| 
Speicher nicht installiert



 a| 
0x56
 a| 
Ungültiger CPU-Typ oder ungültige Geschwindigkeit



 a| 
0x57
 a| 
CPU-Diskrepanz



 a| 
0x58
 a| 
CPU-Selbsttest fehlgeschlagen oder möglicher CPU-Cache-Fehler



 a| 
0x59
 a| 
Der CPU-Mikrocode wurde nicht gefunden oder das Microcode-Update ist fehlgeschlagen



 a| 
0x5A
 a| 
Interner CPU-Fehler



 a| 
0x5B
 a| 
PPI zurücksetzen ist nicht verfügbar



 a| 
0x5C
 a| 
PEI-Phase BMC Selbsttest fehlgeschlagen



 a| 
0xD0
 a| 
CPU-Initialisierungsfehler



 a| 
0xD1
 a| 
Initialisierungsfehler der Nordbrücke



 a| 
0xD2
 a| 
Initialisierungsfehler Südbrücke



 a| 
0xD3
 a| 
Einige Architekturprotokolle sind nicht verfügbar



 a| 
0xD4
 a| 
Fehler bei der PCI-Ressourcenzuweisung. Nicht mehr zur Verfügung.



 a| 
0xD5
 a| 
Kein Speicherplatz für Legacy Option ROM



 a| 
0xD6
 a| 
Es wurden keine Ausgabegeräte für die Konsole gefunden



 a| 
0xD7
 a| 
Es wurden keine Geräte für den Konsoleneingang gefunden



 a| 
0xD8
 a| 
Ungültiges Passwort



 a| 
0xD9
 a| 
Fehler beim Laden der Boot-Option (LoadImage hat Fehler zurückgegeben)



 a| 
0xDA
 a| 
Boot-Option fehlgeschlagen (StartImage-Fehler zurückgegeben)



 a| 
0xDB
 a| 
Flash-Update fehlgeschlagen



 a| 
0xDC
 a| 
Das Rücksetzprotokoll ist nicht verfügbar



 a| 
0xDD
 a| 
DXE-Phase BMC-Selbsttestfehler



 a| 
0xE8
 a| 
MRC: ERR_NO_MEMORY



 a| 
0xE9
 a| 
MRC: ERR_LT_LOCK



 a| 
0xEA
 a| 
MRC: ERR_DDR_INIT



 a| 
0xEB
 a| 
MRC: ERR_MEM_TEST



 a| 
0xEC
 a| 
MRC: ERR_VENDOR_SPECIFIC



 a| 
0xED
 a| 
MRC: ERR_DIMM_COMPAT



 a| 
0xEE
 a| 
MRC: ERR_MRC_COMPATIBILITY



 a| 
0xEF
 a| 
MRC: ERR_MRC_STRUCT



 a| 
0xF0
 a| 
MRC: ERR_SET_VDD



 a| 
0xF1
 a| 
MRC: ERR_IOT_MEM_BUFFER



 a| 
0xF2
 a| 
MRC: ERR_RC_INTERN



 a| 
0xF3
 a| 
MRC: ERR_INVALID_REG_ACCESS



 a| 
0xF4
 a| 
MRC: ERR_SET_MC_FREQ



 a| 
0xF5
 a| 
MRC: ERR_READ_MC_FREQ



 a| 
0x70
 a| 
MRC: ERR_DIMM_CHANNEL



 a| 
0x74
 a| 
MRC: ERR_BIST_CHECK



 a| 
0xF6
 a| 
MRC: ERR_SMBUS



 a| 
0xF7
 a| 
MRC: ERR_PCU



 a| 
0xF8
 a| 
MRC: ERR_NGN



 a| 
0xF9
 a| 
MRC: ERR_INTERLEAVE_FAILURE

|===

