---
permalink: swift/account-operations.html 
sidebar: sidebar 
keywords: swift account operations 
summary: Die folgenden Swift-API-Vorgänge werden bei Accounts durchgeführt. 
---
= Konto-Operationen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die folgenden Swift-API-Vorgänge werden bei Accounts durchgeführt.



== GET Konto

Dieser Vorgang ruft die Containerliste ab, die mit den Statistiken zur Konto- und Kontonutzung verknüpft ist.

Der folgende Parameter für die Anfrage ist erforderlich:

* `Account`


Die folgende Anfrageüberschrift ist erforderlich:

* `X-Auth-Token`


Die folgenden unterstützten Abfrageparameter sind optional:

* `Delimiter`
* `End_marker`
* `Format`
* `Limit`
* `Marker`
* `Prefix`


Eine erfolgreiche Ausführung gibt die folgenden Header mit einer „`HTTP/1.1 204 No Content`“-Antwort zurück, wenn das Konto gefunden wurde und keine Container oder die Containerliste leer ist; oder eine „`HTTP/1.1 200 OK`“-Antwort, wenn das Konto gefunden wurde und die Containerliste nicht leer ist:

* `Accept-Ranges`
* `Content-Length`
* `Content-Type`
* `Date`
* `X-Account-Bytes-Used`
* `X-Account-Container-Count`
* `X-Account-Object-Count`
* `X-Timestamp`
* `X-Trans-Id`




== HEAD Konto

Mit dieser Operation werden Kontoinformationen und Statistiken von einem Swift-Konto abgerufen.

Der folgende Parameter für die Anfrage ist erforderlich:

* `Account`


Die folgende Anfrageüberschrift ist erforderlich:

* `X-Auth-Token`


Bei einer erfolgreichen Ausführung werden die folgenden Header mit einer „`HTTP/1.1 204 No Content`“-Antwort zurückgegeben:

* `Accept-Ranges`
* `Content-Length`
* `Date`
* `X-Account-Bytes-Used`
* `X-Account-Container-Count`
* `X-Account-Object-Count`
* `X-Timestamp`
* `X-Trans-Id`


.Verwandte Informationen
link:monitoring-and-auditing-operations.html["Monitoring und Prüfung von Vorgängen"]
