---
permalink: vmware/index.html 
sidebar: sidebar 
keywords: vmware 
summary: Die Installation eines StorageGRID Systems in einer VMware Umgebung umfasst drei Hauptschritte. 
---
= Installieren von VMware: Übersicht
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Installation eines StorageGRID Systems in einer VMware Umgebung umfasst drei Hauptschritte.

. *Vorbereitung*: Bei der Planung und Vorbereitung führen Sie folgende Aufgaben aus:
+
** Erfahren Sie mehr über die Hardware-, Software-, Virtual Machine-, Storage- und Performance-Anforderungen für StorageGRID.
** Erfahren Sie mehr über die Besonderheiten von link:../network/index.html["StorageGRID Networking"] Damit Sie Ihr Netzwerk entsprechend konfigurieren können.
** Ermitteln und Vorbereiten der physischen Server, die Sie für das Hosten Ihrer StorageGRID Grid Nodes verwenden möchten
** Auf den Servern, die Sie vorbereitet haben:
+
*** Installation von VMware vSphere Hypervisor
*** Konfigurieren Sie die ESX Hosts
*** Installation und Konfiguration von VMware vSphere und vCenter




. *Bereitstellung*: Grid-Knoten mit dem VMware vSphere Web Client bereitstellen. Wenn Sie Grid-Nodes implementieren, werden diese als Teil des StorageGRID Systems erstellt und mit einem oder mehreren Netzwerken verbunden.
+
.. Verwenden Sie den VMware vSphere Web Client, eine VMDK-Datei und eine Reihe von .ovf-Dateivorlagen, um die softwarebasierten Nodes als Virtual Machines (VMs) auf den Servern bereitzustellen, die Sie in Schritt 1 vorbereitet haben.
.. Verwenden Sie das Installationsprogramm für StorageGRID Appliance, um StorageGRID Appliance-Nodes bereitzustellen.
+

NOTE: Hardware-spezifische Installations- und Integrationsanweisungen sind nicht im StorageGRID Installationsverfahren enthalten. Informationen zur Installation von StorageGRID Appliances finden Sie im link:../installconfig/index.html["Schnellstart für die Hardwareinstallation"] Anleitung für das Gerät finden.



. *Konfiguration*: Wenn alle Knoten bereitgestellt wurden, verwenden Sie den Grid Manager, um das Grid zu konfigurieren und die Installation abzuschließen.


Diese Anweisungen empfehlen einen Standardansatz für die Implementierung und Konfiguration eines StorageGRID Systems in einer VMware Umgebung. Siehe auch die Informationen über folgende alternative Ansätze:

* Grid-Nodes in VMware vSphere implementieren – mit dem deploy-vsphere-ovftool.sh Bash-Skript (erhältlich im Installationsarchiv)
* Automatisieren Sie die Implementierung und Konfiguration des StorageGRID Systems mit einem Python-Konfigurationsskript (im Installationsarchiv bereitgestellt).
* Automatisieren Sie die Implementierung und Konfiguration von Appliance-Grid-Nodes mit einem Python-Konfigurationsskript (erhältlich über das Installationsarchiv oder über das Installationsprogramm von StorageGRID Appliance).
* Als fortschrittlicher Entwickler von StorageGRID-Implementierungen sollten Sie die Installation VON REST-APIs verwenden, um die Installation von StorageGRID Grid-Nodes zu automatisieren.

