---
permalink: vmware/required-materials.html 
sidebar: sidebar 
keywords: installation materials vmware 
summary: Bevor Sie StorageGRID installieren, müssen Sie die erforderlichen Materialien erfassen und vorbereiten. 
---
= Erforderliche Materialien
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie StorageGRID installieren, müssen Sie die erforderlichen Materialien erfassen und vorbereiten.

[cols="1a,2a"]
|===
| Element | Hinweise 


 a| 
NetApp StorageGRID Lizenz
 a| 
Sie benötigen eine gültige, digital signierte NetApp Lizenz.

*Hinweis*: Das StorageGRID Installationsarchiv enthält eine kostenlose Lizenz, die keinen Support-Anspruch auf das Produkt bietet.



 a| 
StorageGRID Installationsarchiv
 a| 
Unbedingt link:downloading-and-extracting-storagegrid-installation-files.html["Laden Sie das StorageGRID-Installationsarchiv herunter und extrahieren Sie die Dateien"].



 a| 
VMware Software und Dokumentation
 a| 
Während der Installation verwenden Sie VMware vSphere Web Client, um virtuelle Grid-Knoten auf Virtual Machines zu implementieren. Informationen zu unterstützten Versionen finden Sie im https://imt.netapp.com/matrix/#welcome["NetApp Interoperabilitäts-Matrix-Tool"^].



 a| 
Service-Laptop
 a| 
Das StorageGRID-System wird über einen Service-Laptop installiert der Service-Laptop muss Folgendes haben:

* Netzwerkport
* SSH-Client (z. B. PuTTY)
* link:../admin/web-browser-requirements.html["Unterstützter Webbrowser"]




 a| 
StorageGRID-Dokumentation
 a| 
* link:../release-notes/index.html["Versionshinweise"]
* link:../admin/index.html["Anweisungen für die Administration von StorageGRID"]


|===