---
permalink: admin/changing-browser-session-timeout-interface.html 
sidebar: sidebar 
keywords: browser inactivity timeout, inactive users 
summary: Sie können steuern, ob Grid Manager und Tenant Manager-Benutzer abgemeldet werden, wenn sie länger als eine bestimmte Zeit inaktiv sind. 
---
= Zeitlimit für Inaktivität des Browsers ändern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können steuern, ob Grid Manager und Tenant Manager-Benutzer abgemeldet werden, wenn sie länger als eine bestimmte Zeit inaktiv sind.

.Bevor Sie beginnen
* Sie sind mit einem bei Grid Manager angemeldet link:../admin/web-browser-requirements.html["Unterstützter Webbrowser"].
* Sie haben Root-Zugriffsberechtigung.


.Über diese Aufgabe
Das Zeitlimit für die Inaktivität des Browsers beträgt standardmäßig 15 Minuten. Wenn der Browser eines Benutzers für diese Zeit nicht aktiv ist, wird der Benutzer abgemeldet.

Bei Bedarf können Sie die Sperrzeit erhöhen oder verringern, indem Sie die Option * Inaktive Benutzer abmelden nach* einstellen.

Das Zeitlimit für die Inaktivität des Browsers wird auch durch Folgendes gesteuert:

* Ein separater, nicht konfigurierbarer StorageGRID-Timer, der für die Systemsicherheit enthalten ist. Standardmäßig läuft das Authentifizierungs-Token jedes Benutzers 16 Stunden nach der Anmeldung des Benutzers ab. Wenn die Authentifizierung eines Benutzers abläuft, wird dieser Benutzer automatisch abgemeldet, auch wenn das Zeitlimit für die Inaktivität des Browsers deaktiviert ist oder der Wert für das Browsertimeout nicht erreicht wurde. Um das Token zu erneuern, muss sich der Benutzer erneut anmelden.
* Timeout-Einstellungen für den Identitäts-Provider, vorausgesetzt, Single Sign-On (SSO) ist für StorageGRID aktiviert.
+
Wenn SSO aktiviert ist und der Browser eines Benutzers eine Zeitdauer ausläuft, muss der Benutzer seine SSO-Anmeldeinformationen erneut eingeben, um erneut auf StorageGRID zuzugreifen. Siehe link:configuring-sso.html["Konfigurieren Sie Single Sign-On"].



.Schritte
. Wählen Sie *CONFIGURATION* > *Security* > *Security settings*.
. Wählen Sie die Registerkarte *Browser Inaktivität Timeout*.
. Geben Sie im Feld *Abmelden inaktiver Benutzer nach* einen Browser-Timeout-Zeitraum zwischen 60 Sekunden und 7 Tagen an.
+
Sie können die Zeitüberschreitung des Browsers in Sekunden, Minuten, Stunden oder Tagen angeben.

. Wählen Sie *Speichern*. Wenn ein Browser für die angegebene Zeit inaktiv ist, wird der Benutzer vom Grid Manager oder Tenant Manager abgemeldet.
+
Die neue Einstellung hat keine Auswirkung auf die derzeit angemeldenen Benutzer. Benutzer müssen sich erneut anmelden oder ihre Browser aktualisieren, damit die neue Timeout-Einstellung wirksam wird.


