---
permalink: admin/index.html 
sidebar: sidebar 
keywords: how to administer storagegrid 
summary: Verwenden Sie diese Anweisungen, um ein StorageGRID System zu konfigurieren und zu verwalten. 
---
= Administration StorageGRID: Überblick
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Verwenden Sie diese Anweisungen, um ein StorageGRID System zu konfigurieren und zu verwalten.



== Informationen zu diesen Anweisungen

In diesen Anweisungen wird beschrieben, wie Sie mit dem Grid Manager Gruppen und Benutzer einrichten, Mandantenkonten erstellen, damit S3- und Swift-Client-Applikationen Objekte speichern und abrufen können, StorageGRID-Netzwerke konfigurieren und managen, AutoSupport konfigurieren, Node-Einstellungen verwalten und vieles mehr.

Diese Anweisungen richtet sich an technische Mitarbeiter, die nach der Installation ein StorageGRID System konfigurieren, verwalten und unterstützen.



== Bevor Sie beginnen

* Sie verfügen über allgemeine Kenntnisse des StorageGRID Systems.
* Sie verfügen über ziemlich detaillierte Kenntnisse über Linux-Befehlssells, das Netzwerk und die Einrichtung und Konfiguration von Serverhardware.

