---
permalink: s3/accessing-and-reviewing-audit-logs.html 
sidebar: sidebar 
keywords: access audit logs, review audit logs, view audit logs 
summary: Audit-Meldungen werden von StorageGRID-Diensten generiert und in Text-Log-Dateien gespeichert. API-spezifische Audit-Meldungen in den Audit-Protokollen stellen kritische Daten zum Monitoring von Sicherheit, Betrieb und Performance bereit, die Ihnen bei der Bewertung des Systemzustands helfen können. 
---
= Aufrufen und Prüfen von Prüfprotokollen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Audit-Meldungen werden von StorageGRID-Diensten generiert und in Text-Log-Dateien gespeichert. API-spezifische Audit-Meldungen in den Audit-Protokollen stellen kritische Daten zum Monitoring von Sicherheit, Betrieb und Performance bereit, die Ihnen bei der Bewertung des Systemzustands helfen können.

.Bevor Sie beginnen
* Sie haben spezifische Zugriffsberechtigungen.
* Sie haben die `Passwords.txt` Datei:
* Sie kennen die IP-Adresse eines Admin-Knotens.


.Über diese Aufgabe
Der Name der aktiven Audit-Log-Datei `audit.log`, Und es wird auf Admin-Knoten gespeichert.

Einmal am Tag wird die aktive audit.log-Datei gespeichert und eine neue `audit.log` Datei wird gestartet. Der Name der gespeicherten Datei gibt an, wann sie gespeichert wurde, im Format `_yyyy-mm-dd.txt_`.

Nach einem Tag wird die gespeicherte Datei komprimiert und im Format umbenannt `_yyyy-mm-dd.txt.gz_`, Die das ursprüngliche Datum bewahrt.

Dieses Beispiel zeigt die aktive `audit.log` Datei, Datei des Vortags (`2018-04-15.txt`), und die komprimierte Datei für den Vortag (`2018-04-14.txt.gz`).

[listing]
----
audit.log
2018-04-15.txt
2018-04-14.txt.gz
----
.Schritte
. Melden Sie sich bei einem Admin-Knoten an:
+
.. Geben Sie den folgenden Befehl ein: `ssh admin@_primary_Admin_Node_IP_`
.. Geben Sie das im aufgeführte Passwort ein `Passwords.txt` Datei:
.. Geben Sie den folgenden Befehl ein, um zum Root zu wechseln: `su -`
.. Geben Sie das im aufgeführte Passwort ein `Passwords.txt` Datei:
+
Wenn Sie als root angemeldet sind, ändert sich die Eingabeaufforderung von `$` Bis `#`.



. Gehen Sie zu dem Verzeichnis, das die Audit-Log-Dateien enthält:
+
`cd /var/local/audit/export`

. Sehen Sie sich die aktuelle oder gespeicherte Audit-Protokolldatei nach Bedarf an.

