---
permalink: s3/deprecated-put-bucket-request-modifications-for-compliance.html 
sidebar: sidebar 
keywords: S3 REST API, S3 operations, deprecated bucket requests for compliance 
summary: Das SGCompliance XML-Element ist veraltet. Zuvor könnten Sie dieses benutzerdefinierte StorageGRID-Element in das optionale XML-Anforderungsgremium VON PUT Bucket-Anforderungen integrieren, um einen konformen Bucket zu erstellen. 
---
= Veraltet: PUT Bucket-Request-Änderungen aus Compliance-Gründen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das SGCompliance XML-Element ist veraltet. Zuvor könnten Sie dieses benutzerdefinierte StorageGRID-Element in das optionale XML-Anforderungsgremium VON PUT Bucket-Anforderungen integrieren, um einen konformen Bucket zu erstellen.


IMPORTANT: Die in früheren StorageGRID-Versionen verfügbare Funktion für die StorageGRID-Konformität ist veraltet und wurde durch S3-Objektsperre ersetzt.

link:../s3/use-s3-api-for-s3-object-lock.html["Konfigurieren Sie die S3-Objektsperre über die S3-REST-API"]

link:../ilm/index.html["Objektmanagement mit ILM"]

https://["NetApp Knowledge Base: Management älterer, konformer Buckets für StorageGRID 11.5"^]

Mit aktivierter Compliance können keine neuen Buckets mehr erstellt werden. Die folgende Fehlermeldung wird zurückgegeben, wenn Sie versuchen, die Put Bucket-Anforderung zur Compliance-Erstellung eines neuen Compliance-Buckets zu verwenden:

[listing]
----
The Compliance feature is deprecated.
Contact your StorageGRID administrator if you need to create new Compliant buckets.
----