---
permalink: s3/get-object.html 
sidebar: sidebar 
keywords: get object 
summary: Sie können die S3-GET-Objektanfrage verwenden, um ein Objekt aus einem S3-Bucket abzurufen. 
---
= GET Objekt
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die S3-GET-Objektanfrage verwenden, um ein Objekt aus einem S3-Bucket abzurufen.



== ABRUFEN von Objekten und Objekten mit mehreren Teilen

Sie können das verwenden `partNumber` Parameter anfordern, um einen bestimmten Teil eines mehrteiligen oder segmentierten Objekts abzurufen. Der `x-amz-mp-parts-count` Das Antwortelement gibt an, wie viele Teile das Objekt hat.

Sie können festlegen `partNumber` Zu 1 für segmentierte/mehrteilige Objekte und nicht segmentierte/nicht-mehrteilige Objekte; jedoch der `x-amz-mp-parts-count` Antwortelement wird nur für segmentierte oder mehrteilige Objekte zurückgegeben.



== UTF-8 Zeichen in Benutzermetadaten

StorageGRID parst oder interpretiert die entgangenen UTF-8-Zeichen nicht in benutzerdefinierten Metadaten. GET Requests for an object with escaped UTF-8 characters in user-defined metadata don't return the `x-amz-missing-meta` Kopfzeile, wenn der Schlüsselname oder -Wert nicht druckbare Zeichen enthält.



== Nicht unterstützte Anforderungsüberschrift

Die folgende Anforderungsüberschrift wird nicht unterstützt und kehrt zurück `XNotImplemented`:

* `x-amz-website-redirect-location`




== Versionierung

Wenn A `versionId` unterressource wird nicht angegeben. Der Vorgang ruft die aktuellste Version des Objekts in einem versionierten Bucket ab. Wenn die aktuelle Version des Objekts eine Löschmarkierung ist, wird mit dem ein Status „`not found`“ zurückgegeben `x-amz-delete-marker` Antwortkopfzeile auf gesetzt `true`.



== Kopfzeilen zur serverseitigen Verschlüsselung mit vom Kunden bereitgestellten Verschlüsselungsschlüsseln anfordern (SSE-C)

Verwenden Sie alle drei Kopfzeilen, wenn das Objekt mit einem eindeutigen Schlüssel verschlüsselt ist, den Sie angegeben haben.

* `x-amz-server-side-encryption-customer-algorithm`: Angabe `AES256`.
* `x-amz-server-side-encryption-customer-key`: Geben Sie Ihren Verschlüsselungsschlüssel für das Objekt an.
* `x-amz-server-side-encryption-customer-key-MD5`: Geben Sie den MD5-Digest des Verschlüsselungsschlüssels des Objekts an.



IMPORTANT: Die von Ihnen zur Verfügung gelegten Schlüssel werden niemals gespeichert. Wenn Sie einen Verschlüsselungsschlüssel verlieren, verlieren Sie das entsprechende Objekt. Bevor Sie vom Kunden bereitgestellte Schlüssel zum Schutz von Objektdaten verwenden, sollten Sie die Überlegungen in prüfen link:using-server-side-encryption.html["Serverseitige Verschlüsselung"].



== Verhalten DES GET Object für Cloud-Storage-Pool-Objekte

Wenn ein Objekt in einem gespeichert wurde link:../ilm/what-cloud-storage-pool-is.html["Cloud-Storage-Pool"], Das Verhalten einer GET Object Anfrage hängt vom Zustand des Objekts ab. Siehe link:head-object.html["HEAD Objekt"] Entnehmen.


NOTE: Wenn ein Objekt in einem Cloud-Storage-Pool gespeichert ist und eine oder mehrere Kopien des Objekts auch im Grid vorhanden sind, werden GET-Objektanfragen versuchen, Daten aus dem Grid abzurufen, bevor sie aus dem Cloud-Storage-Pool abgerufen werden.

[cols="1a,1a"]
|===
| Status des Objekts | Verhalten VON GET Object 


 a| 
Objekt, das in StorageGRID aufgenommen wurde, durch ILM jedoch noch nicht evaluiert wurde, oder Objekt, das in einem herkömmlichen Storage-Pool gespeichert ist oder Erasure Coding verwendet
 a| 
`200 OK`

Eine Kopie des Objekts wird abgerufen.



 a| 
Objekt in Cloud-Storage-Pool, ist aber noch nicht in einen Zustand übergegangen, der nicht abrufbar ist
 a| 
`200 OK`

Eine Kopie des Objekts wird abgerufen.



 a| 
Das Objekt wurde in einen nicht aufrufbaren Zustand überführt
 a| 
`403 Forbidden`, `InvalidObjectState`

Verwenden Sie A link:post-object-restore.html["WIEDERHERSTELLUNG VON POSTOBJEKTEN"] Anforderung zur Wiederherstellung des Objektstatus in einem abrufbaren Zustand.



 a| 
Objekt wird aus einem nicht aufrufbaren Zustand wiederhergestellt
 a| 
`403 Forbidden`, `InvalidObjectState`

Warten Sie, bis die Anforderung zur Wiederherstellung DES POSTOBJEKTS abgeschlossen ist.



 a| 
Das Objekt wird im Cloud-Storage-Pool vollständig wiederhergestellt
 a| 
`200 OK`

Eine Kopie des Objekts wird abgerufen.

|===


=== Mehrteilige oder segmentierte Objekte in einem Cloud Storage-Pool

Wenn Sie ein mehrteilige Objekt hochgeladen StorageGRID oder ein großes Objekt in Segmente aufgeteilt haben, bestimmt StorageGRID, ob das Objekt im Cloud-Storage-Pool verfügbar ist, indem Sie eine Teilmenge der Teile oder Segmente des Objekts testen. In manchen Fällen wird eine GET Object-Anforderung möglicherweise falsch zurückgegeben `200 OK` Wenn bereits Teile des Objekts in einen nicht aufrufbaren Zustand überführt wurden oder Teile des Objekts noch nicht wiederhergestellt wurden.

In diesen Fällen:

* Die GET Object-Anforderung gibt möglicherweise einige Daten zurück, stoppt jedoch mitten durch die Übertragung.
* Eine nachfolgende GET Object-Anforderung kann zurückgegeben werden `403 Forbidden`.




== Objekt- und Grid-Replizierung

Wenn Sie verwenden link:../admin/grid-federation-overview.html["Grid-Verbund"] Und link:../tenant/grid-federation-manage-cross-grid-replication.html["Grid-übergreifende Replizierung"] Ist für einen Bucket aktiviert, kann der S3-Client den Replizierungsstatus eines Objekts durch Ausgabe einer GET Object-Anforderung überprüfen. Die Antwort bezieht sich auf das StorageGRID-spezifische `x-ntap-sg-cgr-replication-status` Antwortheader, der einen der folgenden Werte enthält:

[cols="1a,2a"]
|===
| Raster | Replikationsstatus 


 a| 
Quelle
 a| 
* *SUCCESS*: Die Replikation war erfolgreich.
* *AUSSTEHEND*: Das Objekt wurde noch nicht repliziert.
* *FAILURE*: Die Replikation ist mit einem permanenten Fehler fehlgeschlagen. Ein Benutzer muss den Fehler beheben.




 a| 
Ziel
 a| 
*REPLIKAT*: Das Objekt wurde aus dem Quellraster repliziert.

|===

NOTE: StorageGRID unterstützt das nicht `x-amz-replication-status` Kopfzeile.

.Verwandte Informationen
link:s3-operations-tracked-in-audit-logs.html["S3-Vorgänge werden in Prüfprotokollen nachverfolgt"]
