---
permalink: maintain/understanding-adc-service-quorum.html 
sidebar: sidebar 
keywords: storagegrid, recover, adc, adc quorum 
summary: 'Bestimmte Storage-Nodes können an einem Datacenter-Standort möglicherweise nicht außer Betrieb gesetzt werden, falls nach der Ausmusterung zu wenige Services für Administrative Domain Controller \ (ADC\) verbleiben würden. Dieser Service, der auf einigen Storage-Nodes enthalten ist, pflegt Grid-Topologiedaten und stellt Konfigurationsdienste für das Grid bereit. Das StorageGRID System erfordert, dass an jedem Standort und zu jeder Zeit ein Quorum von ADC-Services verfügbar ist.' 
---
= Das ADC-Quorum verstehen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bestimmte Storage-Nodes können an einem Datacenter-Standort möglicherweise nicht außer Betrieb gesetzt werden, falls nach der Ausmusterung zu wenige Dienste des Administrative Domain Controller (ADC) verbleiben würden. Dieser Service, der auf einigen Storage-Nodes enthalten ist, pflegt Grid-Topologiedaten und stellt Konfigurationsdienste für das Grid bereit. Das StorageGRID System erfordert, dass an jedem Standort und zu jeder Zeit ein Quorum von ADC-Services verfügbar ist.

Sie können einen Speicher-Node nicht stilllegen, wenn das Entfernen des Knotens dazu führen würde, dass das ADC-Quorum nicht mehr erfüllt wird. Um das ADC-Quorum während eines Stilllegungsvorgangs zu erfüllen, muss an jedem Datacenter mindestens drei Storage-Nodes über den ADC-Service verfügen. Bei mehr als drei Storage-Nodes an einem Datacenter mit dem ADC-Service muss ein einfacher Großteil dieser Nodes nach der Ausmusterung verfügbar sein ((0.5 * `_Storage Nodes with ADC_`) + 1).

Nehmen Sie beispielsweise an, ein Datacenter-Standort umfasst derzeit sechs Storage-Nodes mit ADC-Services, und Sie möchten drei Storage-Nodes außer Betrieb nehmen. Aufgrund der Quorum-Anforderung des ADC müssen Sie zwei Verfahren zur Deaktivierung durchführen:

* Beim ersten Stilllegen müssen Sie sicherstellen, dass vier Speicherknoten mit ADC-Diensten verfügbar bleiben ((0.5 * 6) +1) . Das bedeutet, dass Sie zunächst nur zwei Storage-Nodes außer Betrieb nehmen können.
* Im zweiten Verfahren können Sie den dritten Speicherknoten entfernen, da das ADC-Quorum jetzt nur noch drei ADC-Dienste benötigt ((0.5 * 4) + 1).


Wenn ein Speicherknoten außer Betrieb gesetzt werden muss, aber aufgrund der ADC-Quorum-Anforderung nicht in der Lage ist, müssen Sie einen neuen Speicherknoten in einer Erweiterung hinzufügen und angeben, dass er über einen ADC-Dienst verfügen soll. Anschließend können Sie den vorhandenen Storage-Node ausmustern.

.Verwandte Informationen
link:../expand/index.html["Erweitern Sie Ihr Raster"]
