---
permalink: expand/rebalancing-erasure-coded-data-after-adding-storage-nodes.html 
sidebar: sidebar 
keywords: erasure coding, EC, rebalancing, site rebalance procedure 
summary: Nachdem Sie Storage Nodes hinzugefügt haben, können Sie das EC-Ausgleichverfahren verwenden, um Fragmente, die mit Löschvorgängen codiert wurden, auf die vorhandenen und neuen Storage-Nodes umzuverteilen. 
---
= Ausgleich von Daten, die im Erasure Coding ausgeführt werden, nach dem Hinzufügen von Storage-Nodes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachdem Sie Storage Nodes hinzugefügt haben, können Sie das EC-Ausgleichverfahren verwenden, um Fragmente, die mit Löschvorgängen codiert wurden, auf die vorhandenen und neuen Storage-Nodes umzuverteilen.

.Bevor Sie beginnen
* Sie haben die Erweiterungsschritte zum Hinzufügen der neuen Speicherknoten abgeschlossen.
* Sie haben die geprüft link:considerations-for-rebalancing-erasure-coded-data.html["Überlegungen zur Lastverteilung bei Daten, die mit Erasure Coding versehen sind"].
* Sie wissen, dass replizierte Objektdaten bei diesem Verfahren nicht verschoben werden und dass beim EC-Ausgleichverfahren die replizierte Datennutzung auf jedem Storage Node nicht berücksichtigt wird, wenn festgestellt wird, wo Daten mit Erasure Coding verschoben werden.
* Sie haben die `Passwords.txt` Datei:


.Was passiert, wenn dieses Verfahren ausgeführt wird
Beachten Sie vor dem Starten des Verfahrens Folgendes:

* Das EC-Ausgleichverfahren startet nicht, wenn ein oder mehrere Volumes offline (unmounted) sind oder online (gemountet) sind, sondern sich in einem Fehlerzustand befinden.
* Das EG-Ausgleichverfahren reserviert vorübergehend einen großen Speicher. Storage-Warnmeldungen werden möglicherweise ausgelöst, aber nach Abschluss des Ausgleichs werden sie gelöst. Wenn nicht genügend Speicherplatz für die Reservierung vorhanden ist, schlägt das EC-Ausgleichverfahren fehl. Speicherreservierungen werden freigegeben, wenn der EC-Ausgleichvorgang abgeschlossen ist, unabhängig davon, ob der Vorgang fehlgeschlagen oder erfolgreich war.
* Wenn ein Volume offline geschaltet wird oder ein Fehler auftritt, während ein EC-Neuausgleich ausgeführt wird, wird der Ausgleichsprozess zum Teil abgeschlossen und es gehen keine Daten verloren. Das EC-Ausgleichverfahren kann an dem Punkt fortgesetzt werden, an dem es beendet wurde, wenn alle Volumes fehlerfrei online sind.
* Wenn das EC-Ausgleichverfahren ausgeführt wird, kann die Performance von ILM-Vorgängen und S3- und Swift-Client-Operationen beeinträchtigt werden.
+

NOTE: S3- und Swift-API-Operationen zum Hochladen von Objekten (oder Objektteilen) können während des EC-Ausgleichs fehlschlagen, wenn sie mehr als 24 Stunden benötigen. PUT-Vorgänge mit langer Dauer schlagen fehl, wenn die geltende ILM-Regel eine ausgewogene oder strikte Platzierung bei der Aufnahme verwendet. Der folgende Fehler wird gemeldet: `500 Internal Server Error`.



.Schritte
. [[review_object_Storage]]Überprüfen Sie die aktuellen Objekt-Storage-Details für den Standort, den Sie ausgleichen möchten.
+
.. Wählen Sie *KNOTEN*.
.. Wählen Sie den ersten Speicherknoten am Standort aus.
.. Wählen Sie die Registerkarte *Storage* aus.
.. Bewegen Sie den Mauszeiger über das Diagramm Speicher verwendet – Objektdaten, um die aktuelle Menge replizierter Daten und mit Löschungscodes versehene Daten auf dem Speicher-Node anzuzeigen.
.. Wiederholen Sie diese Schritte, um die anderen Speicherknoten am Standort anzuzeigen.


. Melden Sie sich beim primären Admin-Node an:
+
.. Geben Sie den folgenden Befehl ein: `ssh admin@_primary_Admin_Node_IP_`
.. Geben Sie das im aufgeführte Passwort ein `Passwords.txt` Datei:
.. Geben Sie den folgenden Befehl ein, um zum Root zu wechseln: `su -`
.. Geben Sie das im aufgeführte Passwort ein `Passwords.txt` Datei:
+
Wenn Sie als root angemeldet sind, ändert sich die Eingabeaufforderung von `$` Bis `#`.



. Starten Sie den Vorgang:
+
`rebalance-data start --site "_site-name_"`

+
Für `"_site-name_"`Geben Sie den ersten Standort an, an dem Sie neue Speicherknoten oder Knoten hinzugefügt haben. Umschließen `site-name` In Angeboten.

+
Der EC-Ausgleichvorgang startet, und eine Job-ID wird zurückgegeben.

. Kopieren Sie die Job-ID.
. Überwachen Sie den Status des EC-Ausgleichs.
+
** So zeigen Sie den Status eines einzelnen EC-Ausgleichs an:
+
`rebalance-data status --job-id _job-id_`

+
Für `_job-id_`Geben Sie die ID an, die beim Start des Verfahrens zurückgegeben wurde.

** So zeigen Sie den Status des aktuellen EC-Ausgleichs und aller zuvor abgeschlossenen Verfahren an:
+
`rebalance-data status`

+
[NOTE]
====
Hilfe zum Befehl zum Ausgleich von Daten erhalten:

`rebalance-data --help`

====


. Führen Sie weitere Schritte aus, basierend auf dem zurückgegebenen Status:
+
** Wenn der Status lautet `In progress`, Der EC-Ausgleichsoperation läuft noch. Sie sollten das Verfahren regelmäßig überwachen, bis es abgeschlossen ist.
+
So zeigen Sie die geschätzte Zeit bis zum Abschluss und den Fertigstellungsgrad für den aktuellen Job an:

+
... Wählen Sie *SUPPORT* > *Tools* > *Metriken*.
... Wählen Sie im Abschnitt Grafana *EC Übersicht*.
... Sehen Sie sich die Dashboards *Grid EC Job Estimated Time to Completion* und *Grid EC Job prozentual Completed* an.


** Wenn der Status lautet `Success`, Optional <<review_object_storage,Prüfen von Objekt-Storage>> Um die aktualisierten Details für die Site anzuzeigen.
+
Daten mit Erasure-Coding-Verfahren sollten nun besser auf die Storage-Nodes am Standort abgestimmt sein.

+
[TIP]
====
Wenn die folgende Meldung angezeigt wird, führen Sie den EC-Ausgleichs-Vorgang erneut aus, bis alle mit der Löschung codierten Daten neu ausgeglichen wurden:

`The moves in this rebalance job have been limited. To rebalance additional data, start EC rebalance again for the same site.`

====
** Wenn der Status lautet `Failure`:
+
... Vergewissern Sie sich, dass alle Speicherknoten am Standort mit dem Raster verbunden sind.
... Überprüfen Sie, ob Warnmeldungen vorliegen, die sich auf diese Speicherknoten auswirken könnten, und beheben Sie sie.
... Starten Sie das EC-Neuausgleich-Verfahren neu:
+
`rebalance-data start –-job-id _job-id_`

... Wenn der Status des EC-Ausgleichs noch immer ist `Failure`, Wenden Sie sich an den technischen Support.




. Wenn das EC-Ausgleichverfahren zu viel Last generiert (beispielsweise sind Ingest-Operationen betroffen), unterbrechen Sie den Vorgang.
+
`rebalance-data pause --job-id _job-id_`

. Wenn Sie das EC-Ausgleichverfahren beenden müssen (z. B. um ein StorageGRID-Software-Upgrade durchzuführen), geben Sie Folgendes ein:
+
`rebalance-data terminate --job-id _job-id_`

+

NOTE: Wenn Sie ein EC-Ausgleichverfahren beenden, verbleiben alle bereits verschobenen Datenfragmente am neuen Standort. Daten werden nicht zurück an den ursprünglichen Speicherort verschoben.

. Wenn Sie Erasure Coding an mehreren Standorten verwenden, führen Sie dieses Verfahren für alle anderen betroffenen Standorte aus.

